version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3100:3000"
    networks:
      - monitor-swagger-stats-with-grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 10g
    volumes:
      - ./prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitor-swagger-stats-with-grafana

networks:
  monitor-swagger-stats-with-grafana:
